id = "tachyons-gitlab"
name = "GitLab"
version = "0.0.1"
schema_version = 1
authors = ["Aboobacker MK <aboobackervyd@gmail.com>"]
description = "My cool extension"
repository = "https://github.com/tachyons/zed-gitlab-duo"

[language_servers.gitlab-duo]
name = "GitLab Duo"
# Listing all languages from https://zed.dev/docs/languages
languages = [
    "Ada",
    "Aiken",
    "Amber",
    "Ansible",
    "AsciiDoc",
    "Assembly",
    "Astro",
    "AWK",
    "Bash",
    "Beancount",
    "Bend",
    "Biome",
    "Blade",
    "Blueprint",
    "BQN",
    "Brainfuck",
    "C",
    "C++",
    "Cadence",
    "Cairo",
    "Cap'n Proto",
    "Cedar",
    "CFEngine policy language",
    "Clojure",
    "CSS",
    "CSV",
    "Cucumber/Gherkin",
    "CUE",
    "Curry",
    "D",
    "Dart",
    "Database Markup Language (DBML)",
    "Deno",
    "Diff",
    "Docker",
    "Earthfile",
    "EJS template",
    "Elisp",
    "Elixir",
    "Elm",
    "Ember",
    "Emmet",
    "Env",
    "Erlang",
    "Exograph",
    "Fish",
    "Fortran",
    "GDScript",
    "Gemini gemtext",
    "Git Firefly",
    "Gleam",
    "GLSL",
    "Go",
    "GraphQL",
    "Groovy",
    "Groq",
    "Haskell",
    "Helm",
    "HTML",
    "INI",
    "Java",
    "JavaScript",
    "JSON",
    "Jsonnet",
    "Julia",
    "Justfiles",
    "Kotlin",
    "LaTeX",
    "Ledger",
    "Less",
    "LilyPond",
    "Liquid",
    "Log",
    "Lox",
    "Lua",
    "Luau",
    "Makefile",
    "Markdown Oxide",
    "Markdown",
    "Marksman",
    "Matlab",
    "Meson",
    "Metals",
    "Navi",
    "NeoCMake",
    "Nginx",
    "Nim",
    "Nix",
    "Noir",
    "Nu",
    "OCaml",
    "Odin",
    "Pact",
    "Pest",
    "PHP",
    "PICA200 assembly",
    "Pkl",
    "PlaydateSDK",
    "Prisma",
    "Proto",
    "PureScript",
    "Python",
    "QML",
    "R",
    "Racket",
    "Rainbow CSV",
    "Rego",
    "Rego",
    "Rescript",
    "ReStructuredText",
    "Roc",
    "Roclang",
    "Ron",
    "Ruby",
    "Rust ",
    "Scala",
    "Scheme",
    "SCSS",
    "Shell Script",
    "Slim",
    "Slint",
    "Smithy",
    "Solidity",
    "SQL",
    "Strace",
    "Svelte",
    "Swift",
    "Swift",
    "Tailwind CSS",
    "Templ",
    "Terraform",
    "Tmux",
    "TOML",
    "Twig",
    "TypeScript",
    "Typst",
    "Uiua",
    "Unison",
    "UnoCSS",
    "Vala",
    "Vale",
    "Verilog",
    "VHS",
    "Vlang",
    "Vue",
    "Wgsl",
    "WIT",
    "XML",
    "YAML",
    "Yara",
    "Yarn",
    "Zig",
]

[slash_commands.duo-ask]
description = "Ask code or concepts using GitLab Duo AI"
requires_argument = true
[slash_commands.duo-refactor]
description = "Refactor code using GitLab Duo AI"
requires_argument = true

[slash_commands.duo-generate-tests]
description = "Generate tests using GitLab Duo AI"
requires_argument = true
